version: "3.8"
services:
  api:
    container_name: clone_web_api
    build:
      context: api
      dockerfile: Dockerfile
    volumes:
      - './api:/app/api'
    ports:
      - "1600:1600"
    depends_on:
      - db
    entrypoint: ["poetry", "run"]
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "1600"]
  fontend:
    container_name: web
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - './web:/app/web'
    ports:
      - "1500:1500"
    expose:
      - 1500
    command: ['npm','run','serve','--','--port','1500']
  db:
    container_name: clone_web_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default
    ports:
      - "1700:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local